name: ocaml-ubuntu

on: [push, pull_request]

jobs:
  build-simple:
    strategy:
      fail-fast: false
      matrix:
        os:
        # - macos-latest # requires changing x86_64-linux, below, to x86_64-macosx
          - ubuntu-latest
        ocaml-compiler:
          - 4.10.2

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true # for coq-proba

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam pin  add coq 8.12.0
      - run: opam pin  add num 1.3

      # dependencies for coq-proba
      - run: opam install coq-stdpp coq-mathcomp-ssreflect coq-flocq menhir

      - run: |
          eval $(opam env);
          ./configure -prefix ./out -clightgen x86_64-linux
          make -j

  #check-stan-admits:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #
  #    - run: sudo apt-get install ripgrep
  #    - run: ./.bin/find-stan-admits
